apiVersion: v1
kind: Pod
metadata:
  name: redis_pod
  labels:
    name: redis_pod
    type: be_pod

spec:
  containers:
    - name: redis_pod
      image: redis
      ports:
        containerPort: 8937
