apiVersion: app/v1
kind: Deployment
metadata:
  name: voting_deployment
  labels:
    name: voting_deployment
    type: be_deployment
spec:
  selectors:
    matchLabel:
      name: voting_pod
      type: be_pod
  replicas: 2
  template:
    metadata:
      name: voting_pod
      labels:
        name: voting_pod
        type: be_pod
    spec:
      containers:
        - name: voting_pod
          image: voting:v1