apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx_deployment
  labels:
    name: nginx_deployment
    tag: be_deployment
spec:
  template:
    metadata:
      name: nginx
      labels:
        name: nginx_pod
        tag: be_pod
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      name: nginx_pod
      tag: be_pod